### ISSUE TITLE
Unable to connect using built-in users

### ISSUE THREAD

**Issue by piwi82** [Pernod70/SYNO.phpPgAdmin#3]
I have just installed phpPgAdmin from CPhub and I get the message `Login disallowed for security reasons.` when I try to connect with both `admin` or `postgres` users.

So I have managed to replace `$conf['extra_login_security'] = true;` by `$conf['extra_login_security'] = false;` in `/usr/syno/synoman/phpsrc/phpPgAdmin/conf/config.inc.php` and now it works.

But I wonder if this is dirty regarding security. Any tought ?

**Comment by Pernod70** [comment]
I connect as admin without problems. See questions #4 and #5 in the phpPgAdmin FAQ at http://phppgadmin.sourceforge.net/doku.php?id=faq

**Comment by piwi82** [comment]
Ok, so it doesn't seem to be so dirty as the workaround I have applied is given in <a href="http://phppgadmin.sourceforge.net/doku.php?id=faq#question_4">#4</a>.

Thanks !
