### ISSUE TITLE
a new package (/version) would be a good thing ...

### ISSUE THREAD

**Issue by Youpidoo54** [Pernod70/SYNO.phpPgAdmin#4]
Hi, 
Hello,
[Since your last,] the versions have been evolving for a long time.
Would it be possible to upgrade your package to Synology DSM6.x=my OS. (not yet v7)
 
Related links : 
https://github.com/phppgadmin/phppgadmin/releases/tag/REL_7-13-0
https://amigotechnotes.wordpress.com/2014/05/17/how-to-create-a-spk-for-synology-dsm-to-distribute-your-lamp/ ...
BUT you know how to do this (me not) ! 
 Thank you in advance. :)

**Comment by Youpidoo54** [comment]
...
![printscreens DMS6 2 4](https://user-images.githubusercontent.com/86771155/124107929-01ffe900-da66-11eb-8ab7-bd65cfa73f16.jpg)
Best regards

**Comment by Pernod70** [comment]
This package is no longer maintained, so there won't be any updates.

**Comment by GwynethLlewelyn** [comment]
So sorry to hear that. Oh well, it was nice while it was available!
